version: '3.9'

networks:
  web:
    external: true

services:
  django:
    build: .
    container_name: mycompany_django
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`easy-platform.cloud`)"
      - "traefik.http.services.django.loadbalancer.server.port=8000"
    networks:
      - internal