api:
  dashboard: true

entryPoints:
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myhttpchallenge
        domains:
          - main: "easy-platform.cloud"
            sans:
              - "*.easy-platform.cloud"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  myhttpchallenge:
    acme:
      email: "d.richter@easy-platform.de"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: websecure

log:
  level: DEBUG

accessLog: {}
